import '@styles/globals.css';
import { Inter } from 'next/font/google';
import Nav from '@components/Nav';
import Provider from '@components/Provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: 'Promtopia',
    template: '%s | Promtopia',
  },
  description: 'Generated by create next app',
}

const RootLayout = ({children}) => {
  return (
    <html lang='en'>
        <body>
            <div className='main'>
                <div className='gradient'/>
            </div>

            <main className='app'>
                <Nav />
                {children}
            </main>
        </body>
    </html>
  )
}

export default RootLayout